import styles from "@/styles/Home.module.css";
import { useAtom } from "jotai";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { scrubScoreAtom } from "../../atoms/criteriaAtom";
import ScrubModal from "../../components/ScrubCriteriaModal";
import ScrubScore from "../../components/ScrubScore";

const inter = Inter({ subsets: ["latin"] });

enum PurchasePattern {
  Unusual = "Unusual",
  Normal = "Normal",
}

export type ScrubScoreResult = {
  score: number;
  walletAddressOrENS: string;
  walletAgeDays: number;
  highestPurchase: number;
  totalPurchases: number;
  purchasePatterns: PurchasePattern;
  socialProfiles: {
    ens: boolean;
    lens: boolean;
    farcaster: boolean;
  };
};

export default function Home() {
  const [searchedValue, setSearchValue] = useState<string>("");
  const [isScrubModalOpen, setScrubModalOpen] = useState(false);
  const [scrubCritera, setScrubCriteria] = useAtom(scrubScoreAtom);
  const [searchResult, setSearchResult] = useState<ScrubScoreResult>();

  async function fetchResults() {
    const scamScore = await fetch(`/api/score`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(scrubCritera),
    });
    const scamScoreJSON = await scamScore.json();
    console.log(scamScoreJSON);
    setSearchResult(scamScoreJSON);
  }

  return (
    <>
      <Head>
        <title>Scrubbie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Image
          src="/Scrubbie.svg"
          alt="Scrubbie Logo"
          width={350}
          height={350}
          priority
        />
        <div
          className={styles.card}
          style={{
            ...(searchResult && {
              minWidth: 950,
            }),
          }}
        >
          <div className={styles.title}>Search to check wallet</div>
          <div className={styles.search}>
            <input
              type="text"
              placeholder="vitalik.eth"
              value={searchedValue || ""}
              onChange={(e) => {
                console.log(e.target.value);
                setSearchValue(e.target.value);
              }}
            />
            <button onClick={() => fetchResults()}>
              <Image
                src="/bubbles.svg"
                alt="search"
                width={45}
                height={40}
                priority
              />
            </button>
          </div>
          {searchResult && <ScrubScore results={searchResult} />}
          <button
            className={styles.customizeButton}
            onClick={() => setScrubModalOpen(true)}
          >
            {`${
              searchResult ? `View or adjust scrub criteria` : `Customize Scrub`
            }`}
          </button>
        </div>

        <div
          style={{
            height: 100,
          }}
        ></div>
        <ScrubModal
          isOpen={isScrubModalOpen}
          onClose={() => setScrubModalOpen(false)}
          scrubCritera={scrubCritera}
          setScrubCriteria={setScrubCriteria}
          fetchResults={fetchResults}
        />
      </main>
    </>
  );
}
